/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SI_Lab2_191553;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        SI_Lab2_191553.App classUnderTest = new SI_Lab2_191553.App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
